[build-system]
requires = ["setuptools >= 61.1.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "A"
description = "Packge A"
dynamic = ["version"]

[tool.setuptools.packages.find]
namespaces = true
