[build-system]
requires = ["setuptools >= 61.1.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "namespace-A"
description = "Namespace Packge A"
dynamic = ["version"]

[tool.setuptools.packages.find]
include = ["A*"]
